### ISSUE TITLE
RuntimeError: Pandoc died with exitcode "64" during conversion: b'JSON parse error\r\n'

### ISSUE THREAD

**Issue by harinjoshi** [bebraw/pypandoc#183] opened 2019-10-03 14:35 UTC
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-f34c8c932f5d> in <module>
     10 import pypandoc
     11 
---> 12 output = pypandoc.convert_file('data.json', 'rst', outputfile = 'nlu.txt')
     13 assert output == ""
     14 print("Method success")

c:\users\harin\miniconda3\lib\site-packages\pypandoc\__init__.py in convert_file(source_file, to, format, extra_args, encoding, outputfile, filters)
    138     format = _identify_format_from_path(source_file, format)
    139     return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
--> 140                           outputfile=outputfile, filters=filters)
    141 
    142 

c:\users\harin\miniconda3\lib\site-packages\pypandoc\__init__.py in _convert_input(source, format, input_type, to, extra_args, outputfile, filters)
    323     if p.returncode != 0:
    324         raise RuntimeError(
--> 325             'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
    326         )
    327 

```

how to resolve this error?please help me out

**Comment by jankatins** [comment] 2020-04-12 23:31
This is a pandoc message, I would guess this is a json format error: does the json pass validation?

Closing because I guess the problem is not relevant anymore.

**Closed by jankatins** 2020-04-12 23:31 UTC

**Comment by svyotov** [comment] 2020-05-26 10:31
I also get the same error with this code `print(pypandoc.convert_text('{"b":"a"}',to="rst", format='json'))`
```
>> print(pypandoc.convert_text('{"b":"a"}',to="rst", format='json'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/doc-maker/lib/python3.8/site-packages/pypandoc/__init__.py", line 100, in convert_text
    return _convert_input(source, format, 'string', to, extra_args=extra_args,
  File "/doc-maker/lib/python3.8/site-packages/pypandoc/__init__.py", line 320, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "64" during conversion: b'JSON parse error\n'
>>> print(pypandoc.convert_text('{"b":"a"}',to="rst", format='json'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/doc-maker/lib/python3.8/site-packages/pypandoc/__init__.py", line 100, in convert_text
    return _convert_input(source, format, 'string', to, extra_args=extra_args,
  File "/doc-maker/lib/python3.8/site-packages/pypandoc/__init__.py", line 320, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "64" during conversion: b'JSON parse error\n'
```
